export const SET_COMPONENTS = 'SET_COMPONENTS';
export const SET_ACTIVE_COMPONENT_ID = 'SET_ACTIVE_COMPONENT_ID';
export const UPDATE_COMPONENT = 'UPDATE_COMPONENT';

export const ADD_COMPONENT = 'ADD_COMPONENT';
export const UPDATE_ACTIVE_COMPONENT = 'UPDATE_ACTIVE_COMPONENT';
export const MOVE_COMPONENT = 'MOVE_COMPONENT';
export const DELETE_ACTIVE_COMPONENT = 'DELETE_ACTIVE_COMPONENT';
export const UPDATE_EDIT_AREA_DRAG_HEIGHT = 'UPDATE_EDIT_AREA_DRAG_HEIGHT';
